### PR TITLE
* I visited the idea. Full replace the "WinAnsiEncoding" on "CP1251" …

### PR DESCRIPTION
**Pull request by aazavid**
…I think it is better to support Russian fonts without any substitutions. I can't test it.

### CODE REVIEW

**Comment by romankassebaum** [comment]
But does it then still support German and English fonts?

**Comment by romankassebaum** [comment]
And the hard cast AnsiString(...) in _Writeln with Russian chars will not work on a German Windows.

**Comment by aazavid** [comment]
I thought the individual files are going for them: PdfGBFonts and PdfJpFonts

**Comment by romankassebaum** [comment]
I see, you are right.

But then we need several _Writeln methods. Instead of casting to an AnsiString the methods have to work with TEncoding.GetEncoding(Codepage).GetBytes.

**Pull request closed without merging**
